// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transport/kafka/kafka.go

// Package transportkafkamock is a generated GoMock package.
package transportkafkamock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	transport "github.com/IordanisCodeExamples/go-api-example/internal/transport"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// IngestMovie mocks base method.
func (m *MockService) IngestMovie(ctx context.Context, movie transport.Movie) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestMovie", ctx, movie)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestMovie indicates an expected call of IngestMovie.
func (mr *MockServiceMockRecorder) IngestMovie(ctx, movie interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestMovie", reflect.TypeOf((*MockService)(nil).IngestMovie), ctx, movie)
}
